#
# This file is part of ligero.
#
# (c) Cesar Darinel  <CesarDarinelOrtiz@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

sudo: false

script: phpunit test/test.php